version: "3"
services:
  postgres_freshmen:
    image: postgres
    container_name: postgres-sql-server-freshmen 
    environment:
      - POSTGRES_DB=so2alak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mans1611
      - POSTGRES_PORT=5432
    volumes:
      - postgres-sql-volume-freshmen:/var/lib/postgresql/data
      - ./so2alak.dump:/backup/so2alak.dump
      - ./datareplication.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
  postgres_s:
    image: postgres
    container_name: postgres-sql-server-fr 
    environment:
      - POSTGRES_DB=so2alak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mans1611
      - POSTGRES_PORT=5434
    volumes:
      - postgres-sql-volume-mans:/var/lib/postgresql/data
    ports:
      - "5434:5434"
  postgres_senior:
    image: postgres
    container_name: postgres-sql-server-senior 
    environment:
      - POSTGRES_DB=so2alak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mans1611
      - POSTGRES_PORT=5433
    volumes:
      - postgres-sql-volume-senior:/var/lib/postgresql/data
      - ./so2alak.dump:/backup/so2alak.dump
      - ./datareplication.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5433:5433"
  rabbitMQ:
      image: rabbitmq:management
      container_name: rabbitMQ 
      ports:
        - "5672:5672"
        - "15672:15672"
  so2alak-server:
    build: .
    volumes:
      - server_postgres-sql-volume:/var/lib/postgresql/data
      - ./:/var/lib/postgres/data
    env_file:
      - ./.env
    depends_on:
      - postgres_senior
      - postgres_freshmen
      - rabbitMQ

  front-end:
    build: ../frontend
    env_file:
      - ../frontend/.env
    ports:
      - "3000:3000"

  

  nginx:
    image: nginx
    container_name: LoadBalancer
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis

volumes:
  postgres-sql-volume-freshmen:
  postgres-sql-volume-senior:
  postgres-sql-volume-mans:
  server_postgres-sql-volume:
